/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import ccomponents.CustomCanvas;
import ccomponents.CustomJPanel;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Graphics;
import models.Signal;

/**
 *
 * @author Cristi
 */
public class FrmMain extends javax.swing.JFrame {

    public CustomCanvas canvas;
    public CustomJPanel panel;
    public Thread th;
    public Signal s1;
    public Signal s2;

    public FrmMain() {
        initComponents();
        this.setSize(600, 800);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
//        canvas = new CustomCanvas(400, 400);
//        this.add(canvas);
//        canvas.setSize(400, 400);
//        canvas.setLocation(20, 20);
//        Color c =new Color(1f,0f,0f,0f);
//        canvas.setBackground(c);
//        canvas.setVisible(true);
        this.s1 = new Signal(50, 0, 4);
//        canvas.setS1(s1);
        this.s2 = new Signal(100, Math.PI/2, 1);
//        canvas.setS2(s2);
        
        panel = new CustomJPanel(500, 500);
        this.add(panel);
        panel.setSize(500, 500);
        panel.setLocation(42, 20);
        panel.setBackground(Color.white);
        panel.setVisible(true);
        panel.setBackground(Color.white);
        panel.setS1(s1);
        panel.setS2(s2);
        
        th = new Thread(this.panel);
//        th = new Thread(this.canvas);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStop = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(btnStart)
                .addGap(28, 28, 28)
                .addComponent(btnStop)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStop)
                    .addComponent(btnStart))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        this.th.start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        this.th.stop();
//        this.remove(this.canvas);
//        canvas = new CustomCanvas(400, 400);
//        this.add(canvas);
//        canvas.setSize(400, 400);
//        canvas.setLocation(20, 20);
//        canvas.setBackground(Color.white);
//        canvas.setVisible(true);
//        canvas.setS1(s1);
//        canvas.setS2(s2);
//        th = new Thread(this.canvas);
        
        this.s1 = new Signal(50, 0, 4);
//        canvas.setS1(s1);
        this.s2 = new Signal(100, Math.PI/2, 1);
//        canvas.setS2(s2);
        this.remove(panel);
        panel = new CustomJPanel(500, 500);
        this.add(panel);
        panel.setSize(500, 500);
        panel.setLocation(42, 20);
        panel.setBackground(Color.white);
        panel.setVisible(true);
        panel.setBackground(Color.white);
        panel.setS1(s1);
        panel.setS2(s2);
        
        th = new Thread(this.panel);
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    // End of variables declaration//GEN-END:variables
}
